---
- name: Ensure rngd-tools are present
  yum: name=rng-tools state=present

- name: Configure rngd to use /dev/urandom since in virtualmachines there usually is no hardware source for random data
  copy: src=etc/systemd/system/rngd.service dest=/etc/systemd/system/rngd.service owner=root group=root

- name: Ensure rngd service is started
  service: name=rngd state=started

- name: Ensure KDC database is created
  command: "kdb5_util create -s -P {{ KRB_DB_PASSWORD }} creates=/var/kerberos/krb5kdc/principal"

- name: Ensure rngd service is stopped
  service: name=rngd state=stopped

# TODO: Only remove if it didn't already exist
- name: Ensure rngd-tools are removed again
  yum: name=rng-tools state=absent
  
