---
# Purpose: Creates the Kerberos principals needed
#
# Notes: 
#   - Executed on KDC server as it requires kadmin.local
#   - The principal database must already exist

- name: Determine existing principals
  shell: kadmin.local -q 'listprincs'
  register: principal_list
  changed_when: false

- name: Ensure Admin principal exists
  command: kadmin.local -q 'addprinc -pw krbsekret {{ KRB_ADMIN }}/admin@{{ KRB_REALM }}'
  when: "KRB_ADMIN ~ '/admin@' ~ KRB_REALM not in principal_list.stdout_lines"
